f = open("ab.txt","r")
temp = f.read()
chars = len(temp)
sentence = len(temp.split())
line = len(temp.splitlines())
print("Number of characters in file: ", chars)
print("Number of sentences in file: ", sentence)
print("Number of lines in file: ", line)
f.close()